spring.application.name=gmopg-json-web
server.port=8080

# GMO-PG API Configuration (Test Environment)
gmo.api.url=https://pt01.mul-pay.jp/payment
gmo.api.pass=59e3e2708cdd699bfc9d3e8029350b4704c43591b52992f428190ee069cebcc1
gmo.site.id=tsite00061795
gmo.site.pass=w7bbdc7y
gmo.shop.id=tshop00077975
gmo.shop.pass=c16726ga
gmo.shop.order.prefix=ORDER
gmo.h2.console.path=http://localhost:8080/h2-console

# H2データベースの接続設定（組み込みモード：アプリ起動時に自動で生成・起動）
spring.datasource.url=jdbc:h2:tcp://localhost/~/gmopg-json-web;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# spring.datasource.generate-unique-name=false

# H2 Console（ブラウザからDBの中身を確認するツール）を有効化
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
